### ISSUE TITLE
Error: Cannot enqueue Query after fatal error.

### ISSUE THREAD

**Issue by evgeny-t** [db-migrate/node-db-migrate#258]
I am trying to apply migrations to an empty database `qwerty`.

I run `db-migrate -e test up` and get 
```
[INFO] Using test settings: { username: '<name>',
  password: '******',
  database: 'qwerty',
  host: '<ip>',
  driver: 'mysql',
  multipleStatements: true }
[INFO] require: ./mysql
[INFO] connecting
[INFO] connected
[INFO] creating table: migrations
[SQL] CREATE TABLE IF NOT EXISTS `migrations` (`id` INTEGER  PRIMARY KEY AUTO_INCREMENT NOT NULL, `name` VARCHAR (255) NOT NULL, `run_on` DATETIME  NOT NULL)
[INFO] migration table created
[INFO] loading migrations from dir C:\bb\dbmig\migrations
[INFO] loading migrations from database

[ERROR] Error: Cannot enqueue Query after fatal error.
    at Protocol._validateEnqueue (C:\Users\TimoshenkoEA\AppData\Roaming\npm\node_modules\db-migrate\node_modules\mysql\l
ib\protocol\Protocol.js:193:16)
    at Protocol._enqueue (C:\Users\TimoshenkoEA\AppData\Roaming\npm\node_modules\db-migrate\node_modules\mysql\lib\proto
col\Protocol.js:129:13)
    at Connection.query (C:\Users\TimoshenkoEA\AppData\Roaming\npm\node_modules\db-migrate\node_modules\mysql\lib\Connec
tion.js:185:25)
    at Class.Base.extend.all (C:\Users\TimoshenkoEA\AppData\Roaming\npm\node_modules\db-migrate\lib\driver\mysql.js:411:
34)
    at Class.Base.extend.allLoadedMigrations (C:\Users\TimoshenkoEA\AppData\Roaming\npm\node_modules\db-migrate\lib\driv
er\mysql.js:421:10)
    at Function.Migration.loadFromDatabase (C:\Users\TimoshenkoEA\AppData\Roaming\npm\node_modules\db-migrate\lib\migrat
ion.js:217:10)
    at C:\Users\TimoshenkoEA\AppData\Roaming\npm\node_modules\db-migrate\lib\migrator.js:103:17
    at C:\Users\TimoshenkoEA\AppData\Roaming\npm\node_modules\db-migrate\lib\migration.js:211:5
    at FSReqWrap.oncomplete (fs.js:99:15)
```

My `database.json` looks like following:
```
{
    "test": {
        "username": "<name>",
        "password": "<password>",
        "database": "qwerty",
        "host": "<ip>",
        "driver": "mysql",
        "multipleStatements": true
    },
    "sql-file": true
}

```

I use:  
node `v0.12.0`  
npm `2.5.1`  
db-migrate `0.9.13`  

Am I doing something wrong or it is a bug?

**Comment by evgeny-t** [comment]
It looks similar to #238.

**Comment by evgeny-t** [comment]
It has to be `user` instead of `username`. My fault. The error message is confusing though.

**Comment by wzrdtales** [comment]
closed via https://github.com/db-migrate/node-db-migrate/commit/85397aa4653c7597d2f2f2ce461bcf3def0f2bc3

**Comment by evgeny-t** [comment]
@wzrdtales I guess it would be better to throw an exception instead of such a workaround. What if someone just misspelled that field name?

**Comment by wzrdtales** [comment]
I don't think so, username and user are alias able, and to throw an exception if someone sets a config variable is an **undefined** behavior. It could be needed for some special configuration of the user, if he uses the same config of his project together with db-migrate.
