### ISSUE TITLE
[ERROR] Error: Cannot enqueue Query after fatal error.

### ISSUE THREAD

**Issue by Chipsi** [db-migrate/node-db-migrate#275]
Hello, I have some problems with migrations. 

- node -v v0.12.3
- npm -v 2.9.1

```
[INFO] Using dev settings: { host: 'localhost',
  database: 'pribe',
  driver: 'mysql',
  multipleStatements: true }
[INFO] require: ./mysql
[INFO] connecting
[INFO] connected
[INFO] creating table: migrations
[SQL] CREATE TABLE IF NOT EXISTS `migrations` (`id` INTEGER  PRIMARY KEY AUTO_INCREMENT NOT NULL, `name` VARCHAR (255) NOT NULL, `run_on` DATETIME  NOT NULL)
[INFO] migration table created
[INFO] loading migrations from dir /Users/Chipso/PhpstormProjects/story/migrations
[INFO] loading migrations from database
[ERROR] Error: Cannot enqueue Query after fatal error.
    at Protocol._validateEnqueue (/Users/Chipso/PhpstormProjects/story/node_modules/db-migrate/node_modules/mysql/lib/protocol/Protocol.js:193:16)
    at Protocol._enqueue (/Users/Chipso/PhpstormProjects/story/node_modules/db-migrate/node_modules/mysql/lib/protocol/Protocol.js:129:13)
    at Connection.query (/Users/Chipso/PhpstormProjects/story/node_modules/db-migrate/node_modules/mysql/lib/Connection.js:185:25)
    at Class.Base.extend.all (/Users/Chipso/PhpstormProjects/story/node_modules/db-migrate/lib/driver/mysql.js:411:34)
    at Class.Base.extend.allLoadedMigrations (/Users/Chipso/PhpstormProjects/story/node_modules/db-migrate/lib/driver/mysql.js:421:10)
    at Function.Migration.loadFromDatabase (/Users/Chipso/PhpstormProjects/story/node_modules/db-migrate/lib/migration.js:217:10)
    at /Users/Chipso/PhpstormProjects/story/node_modules/db-migrate/lib/migrator.js:103:17
    at /Users/Chipso/PhpstormProjects/story/node_modules/db-migrate/lib/migration.js:211:5
```

I have created migration with `db-migrate create init`

Here is my configuration 

```
var async = require('async');
var dbm = global.dbm || require('db-migrate');
var type = dbm.dataType;

exports.up = function(db, callback) {
    async.series([
        db.createTable.bind(db, 'EventSize', {
            id: {
                type: 'int',
                length: 11,
                unsigned: true,
                notNull: true,
                primaryKey: true,
                autoIncrement: true
            },
            name: {
                type: 'string',
                length: 150
            },
            limit:{
                type:'int',
                length: 11
            }

        }),
        db.createTable.bind(db, 'EventCategory', {
            id: {
                type: 'int',
                length: 11,
                unsigned: true,
                notNull: true,
                primaryKey: true,
                autoIncrement: true
            },
            name: {
                type: 'string',
                length: 150
            }

        }),
        db.createTable.bind(db, 'Permissions', {
            id: {
                type: 'int',
                length: 11,
                unsigned: true,
                notNull: true,
                primaryKey: true,
                autoIncrement: true
            },
            name: {
                type: 'string',
                length: 150
            }

        }),
        db.createTable.bind(db, 'AccountCategory', {
            id: {
                type: 'int',
                length: 11,
                unsigned: true,
                notNull: true,
                primaryKey: true,
                autoIncrement: true
            },
            name: {
                type: 'varchar',
                length: 150
            }

        }),
        db.createTable.bind(db, 'UserRole', {
            id: {
                type: 'int',
                length: 11,
                unsigned: true,
                notNull: true,
                primaryKey: true,
                autoIncrement: true
            },
            name: {
                type: 'string',
                length: 150
            }

        }),
        db.createTable.bind(db, 'RoleAccessPermissions', {
            id: {
                type: 'int',
                length: 11,
                unsigned: true,
                notNull: true,
                primaryKey: true,
                autoIncrement: true
            },
            rid: {
                type: 'int',
                length: 11,
                unsigned: true,
                notNull: true,
                foreignKey: {
                    name: 'rid_fk',
                    table: 'UserRole',
                    rules:{
                        onUpdate: 'CASCADE',
                        onDelete: 'RESTRICT'
                    },
                    mapping: 'id'
                }
            },
            pid: {
                type: 'int',
                length: 11,
                unsigned: true,
                notNull: true,
                foreignKey: {
                    name: 'pid_fk',
                    table: 'Permissions',
                    rules:{
                        onUpdate: 'CASCADE',
                        onDelete: 'RESTRICT'
                    },
                    mapping: 'id'
                }
            },
            active: {
                type: 'tinyint',
                length: 1
            }

        }),
        db.createTable.bind(db, 'Events', {
            id: {
                type: 'int',
                length: 31,
                unsigned: true,
                notNull: true,
                primaryKey: true,
                autoIncrement: true
            },
            name: {
                type: 'string',
                length: 150
            },
            eventHash: {
                type: 'string',
                length: 150
            },
            private: {
                type: 'tinyint',
                length: 1
            },
            ownerId: {
                type: 'int',
                length: 31,
                unsigned: true,
                notNull: true
            },
            sizeId: {
                type: 'int',
                length: 11,
                unsigned: true,
                notNull: true,
                foreignKey: {
                    name: 'sizeId_fk',
                    table: 'EventSize',
                    rules:{
                        onUpdate: 'CASCADE',
                        onDelete: 'RESTRICT'
                    },
                    mapping: 'id'
                }
            },
            categoryId: {
                type: 'int',
                length: 11,
                unsigned: true,
                notNull: true,
                foreignKey: {
                    name: 'categoryId_fk',
                    table: 'EventCategory',
                    rules:{
                        onUpdate: 'CASCADE',
                        onDelete: 'RESTRICT'
                    },
                    mapping: 'id'
                }
            }
        })

    ], callback);
};

exports.down = function(db, callback) {
    async.series([
        db.dropTable.bind(db, 'EventSize'),
        db.dropTable.bind(db, 'EventCategory'),
        db.dropTable.bind(db, 'Permissions'),
        db.dropTable.bind(db, 'UserRole'),
        db.dropTable.bind(db, 'AccountCategory'),
        db.dropTable.bind(db, 'RoleAccessPermissions'),
        db.dropTable.bind(db, 'Events')
    ], callback);
};
```

Here is my log.

**Comment by bossqone** [comment]
I've probably found solution.
Original `database.json`:
```json
{
    "dev": {
        "host": "localhost",
        "user": { "ENV" : "root" },
        "password" : { "ENV" : "mypass" },
        "database": "db-name",
        "driver": "mysql",
        "multipleStatements": true
    }
}
```
Modified working version:
```json
{
    "dev": {
        "host": "localhost",
        "user": "root",
        "password" : "mypass",
        "database": "db-name",
        "driver": "mysql",
        "multipleStatements": true
    }
}
```

**Comment by Chipsi** [comment]
@bossqone fixed my problem, you can #close

**Comment by wzrdtales** [comment]
@bossqone Awesome, thanks for helping out here :)

@Chipsi I'm glad your problem was resolved. Closing here
