### ISSUE TITLE
postgres: db:create doesn't work

### ISSUE THREAD

**Issue by mdreizin** [db-migrate/node-db-migrate#307]
`db-migrate db:create test`

```
[INFO] Created database "test"
[ERROR] TypeError: undefined is not a function
    at Class.Base.extend.close (/usr/local/lib/node_modules/db-migrate/lib/driver/pg.js:359:9)
    at null.callback (/usr/local/lib/node_modules/db-migrate/bin/db-migrate:274:12)
    at Query.handleError (/usr/local/lib/node_modules/db-migrate/node_modules/pg/lib/query.js:97:17)
    at null.<anonymous> (/usr/local/lib/node_modules/db-migrate/node_modules/pg/lib/client.js:166:26)
    at emit (events.js:107:17)
    at Socket.<anonymous> (/usr/local/lib/node_modules/db-migrate/node_modules/pg/lib/connection.js:109:12)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
```

`database.json`

```json
{
  "dev": {
    "driver": "pg",
    "host": "localhost"
  }
}
```

What kind of options should be defined to successfully create database?

**Comment by wzrdtales** [comment]
@mdreizin I just discovered there was a fallse quotation in those methods for the pg driver.

I will publish a bugfix shortly

**Comment by wzrdtales** [comment]
bugfix published under v0.9.22

try it again, it should work now

**Comment by mdreizin** [comment]
@wzrdtales Thanks alot for the fix.

if I run `db-migrate db:create test` with the following config:

```json
{
  "dev": {
    "driver": "pg",
    "host": "localhost"
  }
}
```

It will work: `[INFO] Created database "test"`

But if I run the same command with the following config:

```json
{
  "dev": {
    "driver": "pg",
    "host": "localhost",
    "database": "test"
  }
}
```

It will not work:

```
[ERROR] error: database "test" does not exist
    at Connection.parseE (/usr/local/lib/node_modules/db-migrate/node_modules/pg/lib/connection.js:534:11)
    at Connection.parseMessage (/usr/local/lib/node_modules/db-migrate/node_modules/pg/lib/connection.js:361:17)
    at Socket.<anonymous> (/usr/local/lib/node_modules/db-migrate/node_modules/pg/lib/connection.js:105:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
```

**Comment by wzrdtales** [comment]
I agree, this a quite confusing behavior, but this is not "fixable". As it is not a bug of db-migrate and also not really a bug of postgres, but a "feature" if someone want to call it one...

The failure is the following, the pg driver gets the connection parameters, including your database parameter. And the pg driver now throws an error, because the database does not exist yet. You need to provide at least one database that actually exists though, this is due to the nature of postgres, you also can't just switch between databases like you can in MariaDB and various other databases, you need to reconnect instead.

**Comment by mdreizin** [comment]
@wzrdtales Thanks a lot for detailed answer.

As I can see it can be fixed if `db-migrate db:create` command will read `database` from config file and then delete it from `config` variable (from connection params) during connection. That true for `0.9.x`.

Probably it could be implemented under `0.10.x`.

**Comment by wzrdtales** [comment]
Unfortunately no, this wont fix it. If you don't supply a database, the default behavior of pg is to open a database that has the same name as your current user. if this db also does not exist, you still run into a failure.

**Comment by wzrdtales** [comment]
@mdreizin The only thing which might resolve this issue, would be to default to `postgres` as default database.
