### ISSUE TITLE
[ERROR] TypeError: Cannot read property 'rows' of undefined

### ISSUE THREAD

**Issue by tgriffo** [db-migrate/node-db-migrate#321]
Hi all,

I realize that a potentially similar issue has been raised and closed in the past. I've tried with the latest version: 0.10.0-beta.4 and still getting the error so posting this.

The environment: Vagrant hashicorp/precise64 running on a Mac host. psql 9.1.19 (running inside Vagrant machine). Node v5.0.0.

When running a migration up without --dry-run, I get the following error:

[ERROR] TypeError: Cannot read property 'rows' of undefined
    at null.callback (/usr/lib/node_modules/db-migrate-pg/index.js:469:29)
    at Query.handleError (/usr/lib/node_modules/db-migrate-pg/node_modules/pg/lib/query.js:106:17)
    at null.<anonymous> (/usr/lib/node_modules/db-migrate-pg/node_modules/pg/lib/client.js:171:26)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at Socket.<anonymous> (/usr/lib/node_modules/db-migrate-pg/node_modules/pg/lib/connection.js:109:12)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)

When running a migration up with --dry-run, I get the following error:

[INFO] dry run
select version() as version;
SHOW search_path;
SET search_path TO "coxitchas","$user","public";
[ERROR] TypeError: Cannot read property 'rows' of undefined
    at null.callback (/usr/lib/node_modules/db-migrate-pg/index.js:469:29)
    at Query.handleError (/usr/lib/node_modules/db-migrate-pg/node_modules/pg/lib/query.js:106:17)
    at null.<anonymous> (/usr/lib/node_modules/db-migrate-pg/node_modules/pg/lib/client.js:171:26)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at Socket.<anonymous> (/usr/lib/node_modules/db-migrate-pg/node_modules/pg/lib/connection.js:109:12)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)

Any ideas?

**Comment by wzrdtales** [comment]
@tgriffo This is probalby due to something else that does not work, however the all function gets an empty result and is crashing there.

I have just published a patch for the pg driver, which checks for this. Please update to this version, try again and send the new error logs if there are any.

**Comment by tgriffo** [comment]
Hi @wzrdtales thanks heaps mate. All good now!!
