### ISSUE TITLE
Simple runSql isn't working

### ISSUE THREAD

**Issue by warriorkitty** [db-migrate/node-db-migrate#347]
```
var dbm = global.dbm || require('db-migrate');
var type = dbm.dataType;

exports.up = function(db, callback) {
  db.runSql('INSERT INTO users (username, password, first_name, last_name) VALUES ("dlozic", "abc", "Davor", "Lozic")', [], function() {});

  callback();
};

exports.down = function(db, callback) {
  callback();
};
```
```

command: db-migrate up
[ERROR] SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Migration._up (/home/warriorkitty/.nvm/versions/node/v5.1.0/lib/node_modules/db-migrate/lib/migration.js:172:10)
    at Migration.up (/home/warriorkitty/.nvm/versions/node/v5.1.0/lib/node_modules/db-migrate/lib/migration.js:184:8)
    at Object.Migrator.up (/home/warriorkitty/.nvm/versions/node/v5.1.0/lib/node_modules/db-migrate/lib/migrator.js:84:7)
```

**Comment by warriorkitty** [comment]
Sorry, I had a syntax error in another migration. :)

**Comment by wzrdtales** [comment]
No problem,

please also not that your up migration will cause you problems. This is not how node works:

```javscript
exports.up = function(db, callback) {
  db.runSql('INSERT INTO users (username, password, first_name, last_name) VALUES ("dlozic", "abc", "Davor", "Lozic")', [], function() {});

  callback();
};
```

If you do this, db-migrate will call the callback before it will be able to execute db.runSql completely. This will result in sporadically crashing and not working migrations. May be you're more convenient with the Promise style migrations introduced with the v0.10.0-beta.

**Comment by warriorkitty** [comment]
Yeah, I agree with you. This was just my 'starting example'. My code looks much different now.
Thanks anyway. :)
