### ISSUE TITLE
ERROR] TypeError: Cannot read property 'dropDatabase' of undefined

### ISSUE THREAD

**Issue by noon-ehos** [db-migrate/node-db-migrate#359]
$ db-migrate db:drop rgb-lab.net

[ERROR] TypeError: Cannot read property 'dropDatabase' of undefined
    at /tmp/node_modules/db-migrate/api.js:761:9
    at Object.exports.connect (/tmp/node_modules/db-migrate/lib/driver/index.js:95:16)
    at Object.exports.driver (/tmp/node_modules/db-migrate/connect.js:83:10)
    at executeDB (/tmp/node_modules/db-migrate/api.js:743:9)
    at run (/tmp/node_modules/db-migrate/api.js:936:9)
    at Object.dbmigrate.run (/tmp/node_modules/db-migrate/api.js:358:5)
    at /tmp/node_modules/db-migrate/bin/db-migrate:35:11
    at /tmp/node_modules/resolve/lib/async.js:44:21
    at ondir (/tmp/node_modules/resolve/lib/async.js:187:31)
    at onex (/tmp/node_modules/resolve/lib/async.js:93:22)
    at /tmp/node_modules/resolve/lib/async.js:24:18
    at FSReqWrap.oncomplete (fs.js:82:15)

**Comment by noon-ehos** [comment]
not actual, it' only when not installed npm db-migrate-mysql

**Comment by noon-ehos** [comment]
but for create it still actual 

db-migrate db:create rgb-lab.net

[ERROR] TypeError: Cannot read property 'createDatabase' of undefined
    at /tmp/node_modules/db-migrate/api.js:745:9
    at /tmp/node_modules/db-migrate/lib/driver/index.js:109:9
    at Handshake._callback (/tmp/node_modules/db-migrate-mysql/index.js:424:14)
    at Handshake.Sequence.end (/tmp/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Handshake.ErrorPacket (/tmp/node_modules/mysql/lib/protocol/sequences/Handshake.js:103:8)
    at Protocol._parsePacket (/tmp/node_modules/mysql/lib/protocol/Protocol.js:280:23)

**Comment by wzrdtales** [comment]
Please **always** post **all** information needed to reproduce.

used:
- db-migrate version
- node version
- npm version
- used driver + version

And always post the result of a verbose run.

**Comment by noon-ehos** [comment]
"db-migrate": "^0.10.0-beta.11",
node: v5.4.1
npm: 3.3.12
mysql driver
"db-migrate-mysql": "^1.1.6",

**Comment by wzrdtales** [comment]
Verbose run is missing, please also post your configuration (replace sensible information with dummies) as this does not seem to be a bug but a configuration issue,

**Comment by noon-ehos** [comment]
[INFO] Detected and using the projects local version of db-migrate. '/var/www/node_modules/db-migrate/index.js'
[INFO] Using dev settings: { driver: 'mysql',
  user: 'dev',
  password: '******',
  host: 'db',
  database: 'rgb-lab.net',
  multipleStatements: true }
[INFO] require: db-migrate-mysql
[INFO] connecting
[INFO] connected
[SQL] CREATE DATABASE IF NOT EXISTS `rgb-lab`
[INFO] Error: Failed to create database! { [Error: ER_DBACCESS_DENIED_ERROR: Access denied for user 'dev'@'%' to database 'rgb-lab']
  code: 'ER_DBACCESS_DENIED_ERROR',
  errno: 1044,
  sqlState: '42000',
  index: 0 }


seams problem with mysql user rights, and not with db-migrate, thanks for your time and your help

**Comment by wzrdtales** [comment]
Yes this is an easy to fix one ;)

To help yourself, running in verbose mode often reveals the important bit of information.
