### ISSUE TITLE
'callback is not defined' error when running migrations

### ISSUE THREAD

**Issue by jmwright** [db-migrate/node-db-migrate#362]
I was assuming that callback was defined by db-migrate, but when I try to run the migration I've created it says that callback is not defined. I don't understand what I'm missing and couldn't find anyone else who was having the exact same problem. Version: 0.10.0-beta.11
```
$ db-migrate --version
0.10.0-beta.11
$ db-migrate up
[ERROR] ReferenceError: callback is not defined
    at Class.exports.up (/home/jwright/Documents/lcm-hub/migrations/20160325110510-users.js:23:6)
    at Class.<anonymous> (/home/jwright/Documents/lcm-hub/node_modules/db-migrate/lib/skeleton.js:81:41)
    at Promise._execute (/home/jwright/Documents/lcm-hub/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/home/jwright/Documents/lcm-hub/node_modules/bluebird/js/release/promise.js:474:18)
    at new Promise (/home/jwright/Documents/lcm-hub/node_modules/bluebird/js/release/promise.js:77:14)
    at Class.extend._up (/home/jwright/Documents/lcm-hub/node_modules/db-migrate/lib/skeleton.js:65:12)
    at Class.extend.up (/home/jwright/Documents/lcm-hub/node_modules/db-migrate/lib/skeleton.js:149:17)
    at Object.Migrator.up (/home/jwright/Documents/lcm-hub/node_modules/db-migrate/lib/migrator.js:112:14)
    at /home/jwright/Documents/lcm-hub/node_modules/db-migrate/lib/migrator.js:153:25
    at tryCatcher (/home/jwright/Documents/lcm-hub/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/jwright/Documents/lcm-hub/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/home/jwright/Documents/lcm-hub/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/home/jwright/Documents/lcm-hub/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/home/jwright/Documents/lcm-hub/node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (/home/jwright/Documents/lcm-hub/node_modules/bluebird/js/release/promise.js:629:18)
    at /home/jwright/Documents/lcm-hub/node_modules/bluebird/js/release/nodeback.js:42:21
```

**Comment by wzrdtales** [comment]
You have most probably written an invalid migration. Would you mind to post your migration here?
Also always post verbose runs instead, the normal run do not give enough informations.

**Comment by jmwright** [comment]
```javascript
'use strict';

var dbm;
var type;
var seed;

/**
  * We receive the dbmigrate dependency from dbmigrate initially.
  * This enables us to not have to rely on NODE_PATH.
  */
exports.setup = function(options, seedLink) {
  dbm = options.dbmigrate;
  type = dbm.dataType;
  seed = seedLink;
};

exports.up = function(db) {
  db.createTable('users', {
    id: { type: 'int', primaryKey: true },
    name: 'string',
    password: 'string',
    salt: 'string'
  }, callback);
};

exports.down = function(db) {
  db.dropTable('users', callback);
};
```

**Comment by wzrdtales** [comment]
You're mixing old and new migrations. New migrations do use promises and so should you. You can however still use callbacks, but you need to define them, just as you always need to in node. I don't know how experienced you're with node though.

As you're on the beta tree, go with the new migrations and do this instead:

```javascript
'use strict';

var dbm;
var type;
var seed;

/**
  * We receive the dbmigrate dependency from dbmigrate initially.
  * This enables us to not have to rely on NODE_PATH.
  */
exports.setup = function(options, seedLink) {
  dbm = options.dbmigrate;
  type = dbm.dataType;
  seed = seedLink;
};

exports.up = function(db) {
  return db.createTable('users', {
    id: { type: 'int', primaryKey: true },
    name: 'string',
    password: 'string',
    salt: 'string'
  });
};

exports.down = function(db) {
  return db.dropTable('users');
};
```

**Comment by wzrdtales** [comment]
To explain what I mean with you need to define them: As it is common for node, always the last parameter is the callback which gets passed as parameter into the function. You haven't defined this in the param list and used the new body for new migrations, so you ended up with your error.

An old migration had this body:
```javascript
exports.up = function(db, callback) {
};
```

a new one this:
```javascript
exports.up = function(db) {
};
```

**Comment by wzrdtales** [comment]
I think this should answer your question and I hoped it helped you to continue, I will close here for now. Feel free to open new issues if you encounter any other problems.

**Comment by jmwright** [comment]
Thank you.
