### ISSUE TITLE
Warning: a promise was created in a handler but was not returned from

### ISSUE THREAD

**Issue by noonehos** [db-migrate/node-db-migrate#363]
`db-migrate up:dev --verbose`

```
`Warning: a promise was created in a handler but was not returned from it
    at Object.Base.extend.close (/tmp/node_modules/db-migrate-mysql/index.js:388:12)
    at onComplete (/tmp/node_modules/db-migrate/api.js:857:19)
    at /tmp/node_modules/db-migrate/lib/migrator.js:172:11
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at /tmp/node_modules/db-migrate/lib/migrator.js:171:10
    at Query._callback (/tmp/node_modules/db-migrate/lib/migration.js:339:7)
    at Query.Sequence.end (/tmp/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Query._handleFinalResultPacket (/tmp/node_modules/mysql/lib/protocol/sequences/Query.js:144:8)
    at Query.EofPacket (/tmp/node_modules/mysql/lib/protocol/sequences/Query.js:128:8)
    at Protocol._parsePacket (/tmp/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/tmp/node_modules/mysql/lib/protocol/Parser.js:73:12)
    at Protocol.write (/tmp/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/tmp/node_modules/mysql/lib/Connection.js:96:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
`
```

npm 3.3.12
"db-migrate": "^0.10.0-beta.11",
##

**Comment by noon-ehos** [comment]
all works fine. it's just warning but it really confusing me

**Comment by wzrdtales** [comment]
Please always deliver everything needed to reproduce your issue.

In this case please post a verbose run.as this does not deliver enough information. And please ensure  that the formatting of your issues is properly. I edited your issue and put a code block around your stack trace.
