### ISSUE TITLE
Fail to create foreign keys with rule `onDelete` with Postgresql 

### ISSUE THREAD

**Issue by ivawzh** [db-migrate/node-db-migrate#369]
I am trying to translate this migration to db-migrate: https://github.com/Vincit/objection.js/blob/master/examples/express-es7/migrations/20150613161239_initial_schema.js 

I have tried both using `createTable` with `foreignKey` and `addForeignKey` individually, both of them give me error `Cannot read property 'onDelete' of undefined`.

Versions:
```
   "db-migrate": "^0.10.0-beta.11",
    "db-migrate-pg": "^0.1.9",

✗ nvm version
v4.4.2
```

Migration:
```
'use strict';

var dbm;
var type;
var seed;

/**
 * We receive the dbmigrate dependency from dbmigrate initially.
 * This enables us to not have to rely on NODE_PATH.
 */
exports.setup = function(options, seedLink) {
  dbm = options.dbmigrate;
  type = dbm.dataType;
  seed = seedLink;
};

exports.up = function(db) {
  return db.createTable('Person',
    {
      columns: {
        id: { type: 'bigint', primaryKey: true, autoIncrement: true },
        parentId: {
          type: 'bigint',
          unsigned: true,
          foreignKey: {
            name: 'person_parent_id_fk',
            table: 'Person',
            mapping: 'id'
          }
        },
        firstName: 'string',
        lastName: 'string',
        age: 'int',
        address: 'jsonb'
      },
      ifNotExists: true
    }
  ).then(
    () => {
      db.createTable('Movie', {
          id: { type: 'bigint', primaryKey: true, autoIncrement: true },
          name: 'string'
        }
      )
    }
  ).then(
    () => {
      db.createTable('Animal', {
          id: { type: 'bigint', primaryKey: true, autoIncrement: true },
          ownerId: {
            type: 'bigint',
            unsigned: true,
            foreignKey: {
              name: 'animal_owner_id_fk',
              table: 'Person',
              mapping: 'id'
            }
          },
          name: 'string',
          species: 'string'
        }
      )
    }
  ).then(
    () => {
      db.createTable('Person_Movie', {
          id: { type: 'bigint', primaryKey: true, autoIncrement: true },
          personId: {
            type: 'bigint',
            unsigned: true,
            foreignKey: {
              name: 'person_movie_person_id_fk',
              table: 'Person',
              mapping: 'id',
              rules: { onDelete: 'CASCADE' }
            }
          },
          movieId: {
            type: 'bigint',
            unsigned: true,
            foreignKey: {
              name: 'person_movie_movie_id_fk',
              table: 'Movie',
              mapping: 'id',
              rules: { onDelete: 'CASCADE' }
            }
          }
        }
      )
    }
  )
};

exports.down = function(db) {
  return db.dropTable('Person', {})
    .then(() => {
      db.dropTable('Movie', {})
    })
    .then(() => {
      db.dropTable('Animal', {})
    })
    .then(() => {
      db.dropTable('Person_Movie', {})
    })
};

```

Error messages:
```
✗ db-migrate up --verbose
[INFO] Detected and using the projects local version of db-migrate. '/Users/balala/node_modules/db-migrate/index.js'
[INFO] Using dev settings: { driver: 'pg',
  user: 'postgres',
  host: 'localhost',
  database: 'whatever-development',
  schema: 'whatever-development' }
[INFO] require: db-migrate-pg
[INFO] connecting
[INFO] connected
[SQL] select version() as version
[SQL] SHOW search_path
[SQL] SET search_path TO "whatever-development","$user","public"
[SQL] SELECT table_name FROM information_schema.tables WHERE table_name = 'migrations' AND table_schema = 'whatever-development'
[INFO] creating table: migrations
[SQL] CREATE TABLE IF NOT EXISTS "migrations" ("id"   SERIAL PRIMARY KEY NOT NULL, "name" VARCHAR (255) NOT NULL, "run_on" TIMESTAMP  NOT NULL)
[INFO] migration table created
[INFO] loading migrations from dir /Users/balala/migrations
[INFO] loading migrations from database
[SQL] SELECT * FROM "migrations" ORDER BY run_on DESC, name DESC
[INFO] preparing to run up migration: 20160417133959-create-objectionjs-examples
[SQL] BEGIN;
[INFO] creating table: Person
[WARN] Using unknown data type JSONB
[SQL] CREATE TABLE IF NOT EXISTS "Person" ("id"   SERIAL PRIMARY KEY, "parentId" BIGINT  , "firstName" VARCHAR  , "lastName" VARCHAR  , "age" INTEGER  , "address" JSONB  )
[ERROR] TypeError: Cannot read property 'onDelete' of undefined
    at Object.Base.extend.addForeignKey (/Users/balala/node_modules/db-migrate-pg/index.js:390:101)
    at Object.<anonymous> (/Users/balala/node_modules/db-migrate/lib/driver/shadow.js:47:52)
    at tryCatcher (/Users/balala/node_modules/db-migrate/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/balala/node_modules/db-migrate/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/Users/balala/node_modules/db-migrate/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromiseCtx (/Users/balala/node_modules/db-migrate/node_modules/bluebird/js/release/promise.js:596:10)
    at Async._drainQueue (/Users/balala/node_modules/db-migrate/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/Users/balala/node_modules/db-migrate/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/balala/node_modules/db-migrate/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

And the `addForeignKey` way:
```
.then(
    () => {
     db.addForeignKey('Person', 'Person', 'person_parent_id_foreign', {
          'parentId': 'id'
        }
      )
    }
 ).then(
    () => {
      db.addForeignKey('Animal', 'Person', 'animal_person_id_foreign', {
          'ownerId': 'id'
        }
      )
    }
 ).then(
    () => {
      db.addForeignKey('Person_Movie', 'Person', 'person_movie_person_id_foreign', {
          'personId': 'id'
        },
        {
          onDelete: 'CASCADE'
        }
      )
    }
  ).then(
    () => {
      db.addForeignKey('Person_Movie', 'Movie', 'person_movie_movie_id_foreign', {
          'movieId': 'id'
        },
        {
          onDelete: 'CASCADE'
        }
      )
    }
```

**Comment by ivawzh** [comment]
Right, after trying everything and looking into the source code tests. I figured out a way to achieve it. (We really need a much better documentation...)

Solution:
```
'use strict';

var dbm;
var type;
var seed;

/**
 * We receive the dbmigrate dependency from dbmigrate initially.
 * This enables us to not have to rely on NODE_PATH.
 */
exports.setup = function(options, seedLink) {
  dbm = options.dbmigrate;
  type = dbm.dataType;
  seed = seedLink;
};

exports.up = function(db) {
  return db.createTable('Person',
    {
      columns: {
        id: { type: 'bigint', primaryKey: true, autoIncrement: true },
        parentId: {
          type: 'bigint',
          unsigned: true,
          foreignKey: {
            name: 'person_parent_id_fk',
            table: 'Person',
            mapping: 'id',
            rules: { onDelete: 'NO ACTION' }
          }
        },
        firstName: 'string',
        lastName: 'string',
        age: 'int',
        address: 'jsonb'
      },
      ifNotExists: true
    }
  ).then(
    () => {
      db.createTable('Movie', {
          id: { type: 'bigint', primaryKey: true, autoIncrement: true },
          name: 'string'
        }
      )
    }
  ).then(
    () => {
      db.createTable('Animal', {
          id: { type: 'bigint', primaryKey: true, autoIncrement: true },
          ownerId: {
            type: 'bigint',
            unsigned: true,
            foreignKey: {
              name: 'animal_owner_id_fk',
              table: 'Person',
              mapping: 'id',
              rules: { onDelete: 'NO ACTION' }
            }
          },
          name: 'string',
          species: 'string'
        }
      )
    }
  ).then(
    () => {
      db.createTable('Person_Movie', {
          id: { type: 'bigint', primaryKey: true, autoIncrement: true },
          personId: {
            type: 'bigint',
            unsigned: true,
            foreignKey: {
              name: 'person_movie_person_id_fk',
              table: 'Person',
              mapping: 'id',
              rules: { onDelete: 'CASCADE' }
            }
          },
          movieId: {
            type: 'bigint',
            unsigned: true,
            foreignKey: {
              name: 'person_movie_movie_id_fk',
              table: 'Movie',
              mapping: 'id',
              rules: { onDelete: 'CASCADE' }
            }
          }
        }
      )
    }
  )
};

exports.down = function(db) {
  return db.dropTable('Person', {})
    .then(() => {
      db.dropTable('Movie', {})
    })
    .then(() => {
      db.dropTable('Animal', {})
    })
    .then(() => {
      db.dropTable('Person_Movie', {})
    })
};
```

**Comment by wzrdtales** [comment]
> (We really need a much better documentation...)

Agreed, any improvements to the docs and suggestions what should be added and way better every PR is more than welcome :)

I'm glad you figured out how to solve your problem!
