### ISSUE TITLE
Postgresql Error: Connection terminated when DROP CONSTRAINT

### ISSUE THREAD

**Issue by ivawzh** [db-migrate/node-db-migrate#374]
I was trying to write migration to drop unique constraint on a existing column, got the error described below. I am using Postgresql. 

code: 

```
'use strict';

var dbm;
var type;
var seed;

/**
  * We receive the dbmigrate dependency from dbmigrate initially.
  * This enables us to not have to rely on NODE_PATH.
  */
exports.setup = function(options, seedLink) {
  dbm = options.dbmigrate;
  type = dbm.dataType;
  seed = seedLink;
};

exports.up = function(db) {
  return db.createTable('test', {
    columns: {
      name: { type: 'string', notNull: true, unique: true }
    },
    ifNotExists: true
  })
  .then(
    ()=> {
      db.changeColumn('test', 'name', { type: 'string', notNull: true, unique: false })
    }
  )
}

exports.down = function(db, cb) {
  db.dropTable('test', {}, cb)
};
```
db-migrate run --dry-run:

```
[INFO] dry run
select version() as version;
SHOW search_path;
SET search_path TO "db","$user","public";
SELECT table_name FROM information_schema.tables WHERE table_name = 'migrations' AND table_schema = 'db';
CREATE TABLE IF NOT EXISTS "migrations" ("id"   SERIAL PRIMARY KEY NOT NULL, "name" VARCHAR (255) NOT NULL, "run_on" TIMESTAMP  NOT NULL);
SELECT * FROM "migrations" ORDER BY run_on DESC, name DESC;
BEGIN;;
CREATE TABLE IF NOT EXISTS "test" ("name" VARCHAR  NOT NULL UNIQUE);
ALTER TABLE "test" ALTER COLUMN "name" SET NOT NULL;
ALTER TABLE "test" DROP CONSTRAINT "test_name_key";
ALTER TABLE "test" ALTER COLUMN "name" DROP DEFAULT;
ALTER TABLE "test" ALTER COLUMN "name" TYPE VARCHAR USING "name"::VARCHAR;
INSERT INTO "migrations" ("name", "run_on") VALUES ($1, $2) [ [ '/20160512132416-constraintTest',
    Thu May 12 2016 23:35:54 GMT+1000 (AEST) ] ]
[INFO] Processed migration 20160512132416-constraintTest
COMMIT;;
[INFO] Done
```

Error message:

```
✗ db-migrate up
[INFO] Processed migration 20160512132416-constraintTest
[INFO] Done
[ERROR] Error: Connection terminated
    at null.<anonymous> (/Users/me/shit/node_modules/pg/lib/client.js:189:29)
    at g (events.js:260:16)
    at emitNone (events.js:67:13)
    at emit (events.js:166:7)
    at Socket.<anonymous> (/Users/me/shit/node_modules/pg/lib/connection.js:66:10)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at TCP._onclose (net.js:477:12)
```

**Comment by wzrdtales** [comment]
Yes because your are faulty.

First of all do not mixed old styled cb and the new promise behavior, your down function shouldn't look like this.

And second, you used the arrow functions wrong. If you want to return the call directly, then you have to leave out the brackets!

This error was created through your wrong migrations though, as they never have returned.

See the following example how it would look like with the mentoined fixes: 

```javascript
'use strict';

var dbm;
var type;
var seed;

/**
  * We receive the dbmigrate dependency from dbmigrate initially.
  * This enables us to not have to rely on NODE_PATH.
  */
exports.setup = function(options, seedLink) {
  dbm = options.dbmigrate;
  type = dbm.dataType;
  seed = seedLink;
};

exports.up = function(db) {
  return db.createTable('test', {
    columns: {
      name: { type: 'string', notNull: true, unique: true }
    },
    ifNotExists: true
  })
  .then(
    ()=> db.changeColumn('test', 'name', { type: 'string', notNull: true, unique: false })
  )
}

exports.down = function(db, cb) {
  return db.dropTable('test')
};
```

**Comment by ivawzh** [comment]
Thanks
