### ISSUE TITLE
Cannot drop foreign keys -- 0.10.0-beta.20

### ISSUE THREAD

**Issue by benbotto** [db-migrate/node-db-migrate#427]
I can't remove a foreign key.  The following code fails in the down().

```
'use strict';

exports.up = function(db, callback) {
  db
    .addColumn('items', 'stageID', {
      type         : 'int',
      unsigned     : true,
      notNull      : true,
      foreignKey: {
        name   : 'fk_item_stageID',
        table  : 'stages',
        mapping: 'stageID',
        rules  : {
          onDelete: 'CASCADE',
          onUpdate: 'RESTRICT'
        }
      }
    })
    .then(() => callback());
};

exports.down = function(db, callback) {
  db
    .removeForeignKey('items', 'fk_item_stageID') // FAILS HERE
    .then(() => callback());
};
```

Here is what I get when I run the DOWN migration:
```
[INFO] Detected and using the projects local version of db-migrate. '/home/avejidah/programming/cea-exam/node_modules/db-migrate/index.js'
[INFO] Using dev settings: { driver: 'mysql',
  user: '[REDACTED]',
  password: '******',
  database: '[REDACTED]',
  multipleStatements: true }
[INFO] Defaulting to running 1 down migration.
[INFO] require: db-migrate-mysql
[INFO] connecting
[INFO] connected
[INFO] creating table: migrations
[SQL] CREATE TABLE IF NOT EXISTS `migrations` (`id` INTEGER  PRIMARY KEY AUTO_INCREMENT NOT NULL, `name` VARCHAR (255) NOT NULL, `run_on` DATETIME  NOT NULL)
[INFO] loading migrations from database
[SQL] SELECT * FROM `migrations` ORDER BY run_on DESC, name DESC
[INFO] preparing to run down migration: 20161013203234-add-column-stageID-to-items
[SQL] SET AUTOCOMMIT=0;
[SQL] START TRANSACTION;
[SQL] ALTER TABLE `items` DROP FOREIGN KEY `fk_item_stageID`
[ERROR] TypeError: Cannot read property 'dropIndex' of undefined
    at Object.<anonymous> (/home/avejidah/programming/cea-exam/node_modules/db-migrate-mysql/index.js:337:22)
    at tryCatcher (/home/avejidah/programming/cea-exam/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/avejidah/programming/cea-exam/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/avejidah/programming/cea-exam/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/avejidah/programming/cea-exam/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/avejidah/programming/cea-exam/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/home/avejidah/programming/cea-exam/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/home/avejidah/programming/cea-exam/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/home/avejidah/programming/cea-exam/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

Thanks, and let me know if further information is needed.

**Comment by wzrdtales** [comment]
Hey @benbotto ,

First of all, you're using Promises wrong. Secondly, you've identified a bug, I justed pushed out a fix for the driver. Btw. also don't forget to post your driver version, npm version and node version too in your next issues. Those can be important information that might be missing.

Your posted example should look like this instead:

```javascript
'use strict';

exports.up = function(db) {
  return db
    .addColumn('items', 'stageID', {
      type         : 'int',
      unsigned     : true,
      notNull      : true,
      foreignKey: {
        name   : 'fk_item_stageID',
        table  : 'stages',
        mapping: 'stageID',
        rules  : {
          onDelete: 'CASCADE',
          onUpdate: 'RESTRICT'
        }
      }
    });
};

exports.down = function(db) {
  return db
    .removeForeignKey('items', 'fk_item_stageID'):
};
```

Don't mix callback style with promises if not necessary, and if you need to: Use the proper functions instead, those are either `asCallback` or `nodeify`.

Just read through bluebirds really good documentation, that will give you a proper idea of what you have available and how to use it:

http://bluebirdjs.com/docs/getting-started.html

**Comment by benbotto** [comment]
Great, thanks for the prompt fix, and for callback-promises semantics!
