### ISSUE TITLE
No rollback in case of erroneous DDL statements in sql scripts

### ISSUE THREAD

**Issue by arpan-jain** [db-migrate/node-db-migrate#434]
Is there a way to use multiple DDL and DML statements in the same sql script. 
I am using sql files for up and down migrations and i am using MULTIPLE DDL and DML statements in the "up" sql script. The problem is when there is any error during the execution of any DDL statement (eg. CREATE TABLE) all the previous DML statements gets executed (happening due to implicit commit by DDL statements), also the migration does not get recorded in the migrations table, so there is no way to revert the executed statements . Is there a way to handle this? 

test-up.sql :
```
create table `test_table_2`(
`id` int(11) not null auto_increment,
 primary key `id`(`id`)
);

insert into `test_table_2` values(1);

create table `test_table`(
`id` int(11) not null auto_increment,
 primary key `id`(`id`)
);

insert into `test_table_2` values(2);

```

test-down.sql : 

```
 drop table if exists `test_table`;

 drop table if existS `test_table_2`;

```

error:

```
$ db-migrate --config config/database.json up
sql:  CREATE TABLE IF NOT EXISTS `migrations` (`id` INTEGER  PRIMARY KEY AUTO_INCREMENT NOT NULL, `name` VARCHAR (255) NOT NULL, `run_on` DATETIME  NOT NULL)
sql:  SELECT * FROM `migrations` ORDER BY run_on DESC, name DESC
sql:  SET AUTOCOMMIT=0;
sql:  START TRANSACTION;
received data: create table `test_table_2`(
`id` int(11) not null auto_increment,
 primary key `id`(`id`)
);

insert into `test_table_2` values(1);

create table `test_table`(
`id` int(11) not null auto_increment,
 primary key `id`(`id`)
);

insert into `test_table_2` values(2);

sql:  create table `test_table_2`(
`id` int(11) not null auto_increment,
 primary key `id`(`id`)
);

insert into `test_table_2` values(1);

create table `test_table`(
`id` int(11) not null auto_increment,
 primary key `id`(`id`)
);

insert into `test_table_2` values(2);

[ERROR] Error: ER_TABLE_EXISTS_ERROR: Table 'test_table' already exists
    at Query.Sequence._packetToError (/Users/arpan/code/backend_temp/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
    at Query.ErrorPacket (/Users/arpan/code/backend_temp/node_modules/mysql/lib/protocol/sequences/Query.js:83:18)
    at Protocol._parsePacket (/Users/arpan/code/backend_temp/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/Users/arpan/code/backend_temp/node_modules/mysql/lib/protocol/Parser.js:73:12)
    at Protocol.write (/Users/arpan/code/backend_temp/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/arpan/code/backend_temp/node_modules/mysql/lib/Connection.js:96:28)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:534:20)
    --------------------
    at Protocol._enqueue (/Users/arpan/code/backend_temp/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Connection.query (/Users/arpan/code/backend_temp/node_modules/mysql/lib/Connection.js:201:25)
    at /Users/arpan/code/backend_temp/node_modules/db-migrate-mysql/index.js:371:29
    at Promise._execute (/Users/arpan/code/backend_temp/node_modules/db-migrate-mysql/node_modules/bluebird/js/release/debuggability.js:299:9)
    at Promise._resolveFromExecutor (/Users/arpan/code/backend_temp/node_modules/db-migrate-mysql/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/Users/arpan/code/backend_temp/node_modules/db-migrate-mysql/node_modules/bluebird/js/release/promise.js:77:14)
    at Object.Base.extend.runSql (/Users/arpan/code/backend_temp/node_modules/db-migrate-mysql/index.js:366:12)
    at /Users/arpan/code/backend_temp/migrations/20161023064331-add-people.js:32:15
    at tryCatcher (/Users/arpan/code/backend_temp/node_modules/db-migrate/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/arpan/code/backend_temp/node_modules/db-migrate/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/arpan/code/backend_temp/node_modules/db-migrate/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/arpan/code/backend_temp/node_modules/db-migrate/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/arpan/code/backend_temp/node_modules/db-migrate/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/Users/arpan/code/backend_temp/node_modules/db-migrate/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/arpan/code/backend_temp/node_modules/db-migrate/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/arpan/code/backend_temp/node_modules/db-migrate/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
```

**Comment by wzrdtales** [comment]
@arpan-jain This documented here: https://db-migrate.readthedocs.io/en/latest/Getting%20Started/configuration/#important-for-mysql-users

**Comment by arpan-jain** [comment]
I am already using this property in my config file.

database.json

```
{
  "defaultEnv": {
    "ENV": "NODE_ENV"
  },
  "dev": {
    "driver": "mysql",
    "user": "*****",
    "password": "*******",
    "database": "*******,
    "host": "*******",
    "multipleStatements": true
  },
  "stage": {
    "driver": "mysql",
    "user": "*****",
    "password": "*******",
    "database": "********",
    "host": "********",
    "multipleStatements": true
  }
}

**Comment by wzrdtales** [comment]
Then everything should work, where exactly is your problem? Your original issue is a bit to unstructured to get clear about your problem, please try the next time to write a structured issue.

So I will try to answer no sentence by sentence and hope to answer the question you actually had.

> Is there a way to use multiple DDL and DML statements in the same sql script. 

Yes, see the document linked above.

> I am using sql files for up and down migrations and i am using MULTIPLE DDL and DML statements in the "up" sql script. The problem is when there is any error during the execution of any DDL statement (eg. CREATE TABLE) all the previous DML statements gets executed (happening due to implicit commit by DDL statements), also the migration does not get recorded in the migrations table, so there is no way to revert the executed statements.

Yes, but if you don't want to use migrations, and use pure sql instead, you have to expect that this is going to happen. A good migration also does not include multiple actions on the same table though. If the whole thing wents south b/c of syntax errors like those in your examples, you will need to clean those up by yourself.
To keep it short: SQL Files are only supported to make the transition to real migrations easier. You can first just throw your dump as SQL file in and build upon this and afterwards rebuild your migrations. But they are not really intended to be used as a migration, which you can do, but you can't expect that any feature of db-migrate would ever apply as you actually circumvent the API itself. So if you make the decision to use sql files instead of real migrations, you will have basically just the logic for up and down migrations available to you and not much more. The only thing you could hope for is that MariaDB will soon release DDL supporting transactions, which is already a working item though.

As a little hint: If you really want to use SQL Files instead for whatever reason you have, you should stick to best practices. That means: Don't alter a table within the same migration which created it, or in your example don't mix the DML with the DDL.

> Is there a way to handle this?

No, there is not yet an automatic rollback, which will be introduced, but not for migrations like yours. As you're not using the API, we will not be able to record which actions have been executed and are also not available to reverse those. If you would use db-migrate API, we would instead be able to recognize that you called createTable and thus we know that the reverse of createTable is dropTable and thus we can filter out the matching methods from the down function. But we are not going to write a SQL parser to do the same for sql files though.

**Comment by arpan-jain** [comment]
@wzrdtales Thanks, this answers my question. I am indeed trying to create/find a solution which can migrate my database changes from sql scipts itself irrespective of the DDL or DML statements.
Also, sorry for the structure of the question.

**Comment by wzrdtales** [comment]
@arpan-jain 
> Thanks, this answers my question. I am indeed trying to create/find a solution which can migrate my database changes from sql scipts itself irrespective of the DDL or DML statements.

As stated before: Good migrations do follow best practices and the most important one is to only make a single change in the best case per migration. If you would only create your table in the migration file, you would also be able to easily reverse this action. I can just suggest you to use the API of the migration framework you intend to use. No matter if it is this or any other out there though, the API always provides support for many other things and also helps to get a more unified way to handle multiple different dbs.

Also to note: That DDL is not part of transactions currently is just an issue for MySQL and currently also still MariaDB, as far as I know postgres does support this for example.

> Also, sorry for the structure of the question.

No problem, a structured question gets answered faster and you get the answer you search for, as the one working on the issue don't need to invest to much time into reading and understanding your problem :)
