### ISSUE TITLE
TypeError: Promise is not a function

### ISSUE THREAD

**Issue by imrenagi** [db-migrate/node-db-migrate#435]
I tried to run `db-migrate up -e env_name` and then I get the `TypeError:Promise is not a function`. 
I already installed promise library in my computer. but, this error still happens.Any clue about it?

here it is the error:

```
[ERROR] TypeError: Promise is not a function
  at [object Object].exports.up (/home/ubuntu/ESN-F16-SA2/migrations/20161015195530-add-users.js:23:10)
  at [object Object].Migration._up (/opt/circleci/nodejs/v4.1.2/lib/node_modules/db-migrate/lib/migration.js:172:32)
  at [object Object].Migration.up (/opt/circleci/nodejs/v4.1.2/lib/node_modules/db-migrate/lib/migration.js:184:8)
  at Object.Migrator.up (/opt/circleci/nodejs/v4.1.2/lib/node_modules/db-migrate/lib/migrator.js:84:7)
  at /opt/circleci/nodejs/v4.1.2/lib/node_modules/db-migrate/lib/migrator.js:116:18
  at Class.module.exports.Class.extend.startMigration (/opt/circleci/nodejs/v4.1.2/lib/node_modules/db-migrate/lib/driver/base.js:278:32)
  at /opt/circleci/nodejs/v4.1.2/lib/node_modules/db-migrate/lib/migrator.js:115:23
  at iterate (/opt/circleci/nodejs/v4.1.2/lib/node_modules/db-migrate/node_modules/async/lib/async.js:146:13)
  at Object.async.eachSeries (/opt/circleci/nodejs/v4.1.2/lib/node_modules/db-migrate/node_modules/async/lib/async.js:162:9)
  at /opt/circleci/nodejs/v4.1.2/lib/node_modules/db-migrate/lib/migrator.js:113:15
  at Query._callback (/opt/circleci/nodejs/v4.1.2/lib/node_modules/db-migrate/lib/migration.js:228:5)
  at Query.Sequence.end (/opt/circleci/nodejs/v4.1.2/lib/node_modules/db-migrate/node_modules/mysql/lib/protocol/sequences/Sequence.js:85:24)
  at Query._handleFinalResultPacket (/opt/circleci/nodejs/v4.1.2/lib/node_modules/db-migrate/node_modules/mysql/lib/protocol/sequences/Query.js:144:8)
  at Query.EofPacket (/opt/circleci/nodejs/v4.1.2/lib/node_modules/db-migrate/node_modules/mysql/lib/protocol/sequences/Query.js:128:8)
  at Protocol._parsePacket (/opt/circleci/nodejs/v4.1.2/lib/node_modules/db-migrate/node_modules/mysql/lib/protocol/Protocol.js:280:23)
  at Parser.write (/opt/circleci/nodejs/v4.1.2/lib/node_modules/db-migrate/node_modules/mysql/lib/protocol/Parser.js:74:12)
  at Protocol.write (/opt/circleci/nodejs/v4.1.2/lib/node_modules/db-migrate/node_modules/mysql/lib/protocol/Protocol.js:39:16)
  at Socket.<anonymous> (/opt/circleci/nodejs/v4.1.2/lib/node_modules/db-migrate/node_modules/mysql/lib/Connection.js:109:28)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:110:10)
  at TCP.onread (net.js:523:20)
```
##

**Comment by wzrdtales** [comment]
Hey @imrenagi,

unfortunately we can't help you if you don't provide us all informations necessary to reproduce your case.

This means, **always** post:

- used node version
- used npm version
- used db-migrate version
- used driver and its version
- used plugins
- full output of the verbose run
- in complex cases a full gist, as an executable proof
- if necessary used migrations and configuration details (**replace sensible informations before posting configs!**)
- if necessary code samples

As soon as you provide us all information needed, we have an easy way to reproduce your problem and provide you with the help or bugfix you need.

Thank you.

**Comment by imrenagi** [comment]
I've found a way to fixed it. Previously, I installed by using `npm install db-migrate -g`. Then, it gave me those errors. Then I tried to use `npm install db-migrate --save` and everything works now. Should I keep providing the answer for your question above?
