### ISSUE TITLE
ER_INVALID_DEFAULT if more then one column is from type 'timestamp'

### ISSUE THREAD

**Issue by pc-jedi** [db-migrate/node-db-migrate#436]
I found a reproducible error. If you have more then one column from type 'timestamp' the following error occurs:
```
[ERROR] Error: ER_INVALID_DEFAULT: Invalid default value for 'field2'
    at Query.Sequence._packetToError (/home/xxxxx/Projects/test/node_modules/mysql/lib/protocol/sequences/Sequence.js:51:14)
    at Query.ErrorPacket (/home/xxxxx/Projects/test/node_modules/mysql/lib/protocol/sequences/Query.js:83:18)
    at Protocol._parsePacket (/home/xxxxx/Projects/test/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/home/xxxxx/Projects/test/node_modules/mysql/lib/protocol/Parser.js:74:12)
    at Protocol.write (/home/xxxxx/Projects/test/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/xxxxx/Projects/test/node_modules/mysql/lib/Connection.js:109:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
    --------------------
    at Protocol._enqueue (/home/xxxxx/Projects/test/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Connection.query (/home/xxxxx/Projects/test/node_modules/mysql/lib/Connection.js:214:25)
    at /home/xxxxx/Projects/test/node_modules/db-migrate-mysql/index.js:371:29
    at Promise._execute (/home/xxxxx/Projects/test/node_modules/bluebird/js/release/debuggability.js:299:9)
    at Promise._resolveFromExecutor (/home/xxxxx/Projects/test/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/home/xxxxx/Projects/test/node_modules/bluebird/js/release/promise.js:77:14)
    at Object.runSql (/home/xxxxx/Projects/test/node_modules/db-migrate-mysql/index.js:366:12)
    at Object.createTable (/home/xxxxx/Projects/test/node_modules/db-migrate-base/index.js:213:17)
    at Object.<anonymous> (/home/xxxxx/Projects/test/node_modules/db-migrate/lib/driver/shadow.js:37:52)
    at tryCatcher (/home/xxxxx/Projects/test/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/xxxxx/Projects/test/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/xxxxx/Projects/test/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromiseCtx (/home/xxxxx/Projects/test/node_modules/bluebird/js/release/promise.js:604:10)
    at Async._drainQueue (/home/xxxxx/Projects/test/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/home/xxxxx/Projects/test/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/home/xxxxx/Projects/test/node_modules/bluebird/js/release/async.js:17:14)
```

The following migration is one example that causes the error.
```javascript
'use strict';

var dbm;
var type;
var seed;

/**
 * We receive the dbmigrate dependency from dbmigrate initially.
 * This enables us to not have to rely on NODE_PATH.
 */
exports.setup = function (options, seedLink) {
    dbm  = options.dbmigrate;
    type = dbm.dataType;
    seed = seedLink;
};

exports.up = function (db) {
    return db.createTable('test', {
        field1: { type: 'timestamp', notNull: true },
        field2: { type: 'timestamp', notNull: true }
    });
};

exports.down = function (db) {
    return db.dropTable('test', []);
};

exports._meta = {
    "version": 1
};

```

Installed version:
db-migrate: 0.10.0-beta.20
db-migrate-mysql: 1.1.10

**Comment by pc-jedi** [comment]
verbose run result:
```
[INFO] Detected and using the projects local version of db-migrate. '/home/xxxxx/Projects/test/node_modules/db-migrate/index.js'
[INFO] Environment variable MYSQL_ROOT_PASSWORDis empty!
[INFO] Environment variable PRODUCTION_USERNAMEis empty!
[INFO] Environment variable PRODUCTION_PASSWORDis empty!
[INFO] Using dev settings: { driver: 'mysql',
  host: 'localhost',
  user: 'root',
  password: '******',
  database: 'test' }
[INFO] require: db-migrate-mysql
[INFO] connecting
[INFO] connected
[INFO] loaded extra config for migration subfolder: "test/config.json"
[SQL] USE `test`
[INFO] creating table: migrations
[SQL] CREATE TABLE IF NOT EXISTS `migrations` (`id` INTEGER  PRIMARY KEY AUTO_INCREMENT NOT NULL, `name` VARCHAR (255) NOT NULL, `run_on` DATETIME  NOT NULL)
[INFO] migration table created
[INFO] loading migrations from dir /home/xxxxx/Projects/test/migrations/test
[INFO] loading migrations from database
[SQL] SELECT * FROM `migrations` ORDER BY run_on DESC, name DESC
[INFO] preparing to run up migration: 20161024125553-test
[SQL] SET AUTOCOMMIT=0;
[SQL] START TRANSACTION;
[INFO] creating table: test
[SQL] CREATE TABLE  `test` (`field1` TIMESTAMP  NOT NULL, `field2` TIMESTAMP  NOT NULL)
[ERROR] Error: ER_INVALID_DEFAULT: Invalid default value for 'field2'
    at Query.Sequence._packetToError (/home/xxxxx/Projects/test/node_modules/mysql/lib/protocol/sequences/Sequence.js:51:14)
    at Query.ErrorPacket (/home/xxxxx/Projects/test/node_modules/mysql/lib/protocol/sequences/Query.js:83:18)
    at Protocol._parsePacket (/home/xxxxx/Projects/test/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/home/xxxxx/Projects/test/node_modules/mysql/lib/protocol/Parser.js:74:12)
    at Protocol.write (/home/xxxxx/Projects/test/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/xxxxx/Projects/test/node_modules/mysql/lib/Connection.js:109:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
    --------------------
    at Protocol._enqueue (/home/xxxxx/Projects/test/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Connection.query (/home/xxxxx/Projects/test/node_modules/mysql/lib/Connection.js:214:25)
    at /home/xxxxx/Projects/test/node_modules/db-migrate-mysql/index.js:371:29
    at Promise._execute (/home/xxxxx/Projects/test/node_modules/bluebird/js/release/debuggability.js:299:9)
    at Promise._resolveFromExecutor (/home/xxxxx/Projects/test/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/home/xxxxx/Projects/test/node_modules/bluebird/js/release/promise.js:77:14)
    at Object.runSql (/home/xxxxx/Projects/test/node_modules/db-migrate-mysql/index.js:366:12)
    at Object.createTable (/home/xxxxx/Projects/test/node_modules/db-migrate-base/index.js:213:17)
    at Object.<anonymous> (/home/xxxxx/Projects/test/node_modules/db-migrate/lib/driver/shadow.js:37:52)
    at tryCatcher (/home/xxxxx/Projects/test/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/xxxxx/Projects/test/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/xxxxx/Projects/test/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromiseCtx (/home/xxxxx/Projects/test/node_modules/bluebird/js/release/promise.js:604:10)
    at Async._drainQueue (/home/xxxxx/Projects/test/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/home/xxxxx/Projects/test/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/home/xxxxx/Projects/test/node_modules/bluebird/js/release/async.js:17:14)
```

**Comment by wzrdtales** [comment]
Hey @pc-jedi,

in this case this seems to be a problem with your used database and not db-migrate. I just tried to reproduce your example and it is impossible for me to reproduce this. But I am using MariaDB 10.1.x which you probably do not. 

I suggest you to try to upgrade your database to the latest available version, this is not a problem of db-migrate though. As far as I remember MySQL does have, I don't know if it is still a fact though, some problems with timestamps though. 

You might read in their docs, about timestamp and their initialization, I guess you will be able to find a solution or at least a reason for this behavior:
http://dev.mysql.com/doc/refman/5.7/en/timestamp-initialization.html


Another alternative would be to switch away from MySQL to MariaDB, but this a decision you have to make, I do at least always suggest to use MariaDB instead of MySQL, just due to the fact that MySQL is operated through oracle and MariaDB is being developed by the original MySQL developers that developed it before oracle bought sun. But as stated, that is a decision you have to made, that is just my opinion :)
