### ISSUE TITLE
Error "Cannot read property 'split' of undefined" when doing migration with db-migrate module in postgres database

### ISSUE THREAD

**Issue by jun1111** [db-migrate/node-db-migrate#446]
I followed the documentation here to try to migrate a schema in my postgres database using module db-migrate. 
https://umigrate.readthedocs.io/projects/db-migrate/en/latest/API/programable/

Here is the code snippet:
```javascript
const dbMigrate = require('db-migrate');
module.exports.run_migration = function *run_migration(...) {
  const options = {
    cwd: './foldername',
    config: {
      dev: {
        driver: 'pg',
        user: 'xxx',
        password: 'xxx',
        host: 'xxx',
        database: 'xxx',
        schema: 'xxx'
      }
    }
  };
  var dbmigrate = dbMigrate.getInstance(true, options, callback);
  yield dbmigrate.run();
};
```

I got the following error:
error ...... : ErrorStack=TypeError: Cannot read property 'split' of undefined
    at run (......\node_modules\db-migrate\api.js:1150:20)
    at Object.dbmigrate.run (......\node_modules\db-migrate\api.js:530:5)
    at Object.run_migration (......\dbMigrate.js:33:19)

The versions that I am using:
    "db-migrate": "0.10.0-beta.20",
    "db-migrate-pg": "0.1.11",

This seems to suggest that I have not specified a type of the migration, in the code. I am trying to do an "up" migration here. Could you help?

**Comment by jun1111** [comment]
I have changed to used the "up" function instead of the "run" function and was able to do the migration successfully.
