### ISSUE TITLE
Unable to use autoIncrement targeting postgres

### ISSUE THREAD

**Issue by worldspawn** [db-migrate/node-db-migrate#461]
Hi I have a column spec:

`streamRevision: { type: 'bigint', unique: true, unsigned: true, autoIncrement: true },`

Fails with 

```
[ERROR] error: syntax error at or near "UNIQUE"
    at Connection.parseE (C:\Users\critc\AppData\Roaming\npm\node_modules\db-migrate-pg\node_modules\pg\lib\connection.js:539:11)
```

`0.10.0-beta.20`

If i remove autoIncrement it works. I found a similar open issue about auto increment however it seemed to be saying it failed when the length parameter was specified. Here i'm not specifying it.

If i remove unsigned theres no change.
If i remove unique I get 

```
[ERROR] error: syntax error at or near ","
    at Connection.parseE (C:\Users\critc\AppData\Roaming\npm\node_modules\db-migrate-pg\node_modules\pg\lib\connection.js:539:11)
```

This one `streamRevision: { type: 'bigint', unsigned: true, unique: true, notNull: true, autoIncrement: true },` yields

```
[ERROR] error: syntax error at or near "NOT"
    at Connection.parseE (C:\Users\critc\AppData\Roaming\npm\node_modules\db-migrate-pg\node_modules\pg\lib\connection.js:539:11)
```

Is there some way to make it output the complete sql that is failing? Be nice too if the error specified what migration was running when the failure occurred.

**Comment by worldspawn** [comment]
I found the --dry-run arg.

```CREATE TABLE  "aggregate_event" ("aggregate_id" UUID  , "version" BIGINT  , "streamRevision"   UNIQUE, "aggregate" VARCHAR (128) NOT NULL, "type" VARCHAR (128) NOT NULL, "props" TEXT  NOT NULL, PRIMARY KEY ("aggregate_id", "version"));```

from

`streamRevision: { type: 'bigint', unique:true, autoIncrement: true },`

As you can see there is no type being output.

**Comment by worldspawn** [comment]
https://github.com/db-migrate/pg/blob/master/index.js#L42

`var type = spec.autoIncrement ? '' : this.mapDataType(spec.type);`

That would appear to be the reason. Seems quite deliberate, any reason?

**Comment by worldspawn** [comment]
After reading up on how postgres does auto increment I'd suggest this:

``` js
createColumnDef: function(name, spec, options, tableName) {
        var type;
        if (spec.autoIncrement) {
            switch (spec.type) {
                case type.BIGINT:
                    type = 'BIGSERIAL';
                    break;
                case type.SMALLINT:
                    type = 'SMALLSERIAL';
                    break;
                default:
                    type = 'SERIAL';
                    break;
            }
        }
        else {
            type = this.mapDataType(spec.type);
        }

        var len = spec.length ? util.format('(%s)', spec.length) : '';
        var constraint = this.createColumnConstraint(spec, options, tableName, name);
        if (name.charAt(0) != '"') {
            name = '"' + name + '"';
        }

        return { foreignKey: constraint.foreignKey,
                 constraints: [name, type, len, constraint.constraints].join(' ') };
    },
```

**Comment by worldspawn** [comment]
https://github.com/db-migrate/pg/pull/13
