### ISSUE TITLE
sync operation with scope will fail with 'cannot find module' when migrate down

### ISSUE THREAD

**Issue by jshencode** [db-migrate/node-db-migrate#471]
using version 0.10.0-beta.20

## command
```
db-migrate sync:test 20170330114201 --env staging --migrations-dir /Users/jianshen/projects/apollo/shared_schema/migrations --verbose --dry-run --config /Users/jianshen/temporary/database.json
```

## error
```
[ERROR] Error: Cannot find module '/Users/jianshen/projects/apollo/shared_schema/migrations/test/test/20170330132412-add-testtable-column-foo'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Class.extend.setup (/Users/jianshen/projects/apollo/apollo-manager/node_modules/db-migrate/lib/skeleton.js:157:12)
    at /Users/jianshen/projects/apollo/apollo-manager/node_modules/db-migrate/lib/migrator.js:220:33
    at tryCatcher (/Users/jianshen/projects/apollo/apollo-manager/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/jianshen/projects/apollo/apollo-manager/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/jianshen/projects/apollo/apollo-manager/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/jianshen/projects/apollo/apollo-manager/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/jianshen/projects/apollo/apollo-manager/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/Users/jianshen/projects/apollo/apollo-manager/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/jianshen/projects/apollo/apollo-manager/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues (/Users/jianshen/projects/apollo/apollo-manager/node_modules/bluebird/js/release/async.js:17:14)
    at process._tickCallback (node.js:419:13)
```

**Comment by wzrdtales** [comment]
@jshencode Thanks for reporting this! I will need to verify this, going to have look at this though.

**Comment by tothesky8787** [comment]
I could experience the similar problem.
So I did create new migration script and then run db-migrate up once.
Later I tried to run db-migrate reset, and I got similar error: "[ERROR] Error: Cannot find module '/home/app/migrations/20170419110930-hello.js' ...
It was a very headache and I could resolve this error by complete uninstall and then install again.
Anyway, I am curious to know why it happened and what is the best/easiest way to resolve.
Thanks in advance.

**Comment by pjivers** [comment]
The same thing happened to me after I renamed one of my migration files, and later did `db-migrate reset`. It's like the filenames for migrations are being cached somewhere. 🤔  Even a complete re-install didn't fix it.

**Comment by wzrdtales** [comment]
@firstor This would be typical user error and not a bug. You should never rename a migration you already executed. The default action is getting the information of the executed migration from the database. It doesn't gets cached, it is just the way it works. Resolving this would require you to either rename your migration again or go in your database and delete the specific entry from the migrations table.
