### ISSUE TITLE
Using 'up:all'  errors with a zero-length delimiter

### ISSUE THREAD

**Issue by TheNeikos** [db-migrate/node-db-migrate#484]
When I run the following command it fails:

```
db-migrate up:all
```
with the following:

```
[INFO] Enter scope "/"
[INFO] No migrations to run
[INFO] Enter scope "migrations/<name of scope>/sqls"
[INFO] Done
[ERROR] error: zero-length delimited identifier at or near """"
    at Connection.parseE (/home/neikos/projects/webdev/<name>_backend/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/home/neikos/projects/webdev/<name>_backend/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/home/neikos/projects/webdev/<name>_backend/node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at Socket.Readable.push (_stream_readable.js:197:10)
    at TCP.onread (net.js:589:20)
```

This effectively makes it useless.

**Comment by wzrdtales** [comment]
Hey @TheNeikos,

unfortunately we can't help you if you don't provide us all informations necessary to reproduce your case.

This means, **always** post:
- used node version
- used npm version
- used db-migrate version
- used driver and its version
- used plugins
- full output of the verbose run
- in complex cases a full gist, as an executable proof
- if necessary used migrations and configuration details (**replace sensible informations before posting configs!**)
- if necessary code samples

As soon as you provide us all information needed, we have an easy way to reproduce your problem and provide you with the help or bugfix you need.

Thank you.

**Comment by wzrdtales** [comment]
This issue is being closed due to missing responses and insufficient information. Feel free to reopen when you're ready to provide those @TheNeikos
