### ISSUE TITLE
unable to create migration when using db-migrate as a module

### ISSUE THREAD

**Issue by TsvetomirGeorgiev** [db-migrate/node-db-migrate#493]
Code:
const dbmigrate = DBMigrate.getInstance(true, config.migrate);
dbmigrate.setConfigParam('_', []);
dbmigrate.create(migrationName).catch(console.error);

Exception thrown:
[ERROR] TypeError: Cannot read property 'getUTCFullYear' of undefined
    at formatDate (..\node_modules\db-migrate\lib\skeleton.js:23:9)
    at Class.formatName (..\node_modules\db-migrate\lib\skeleton.js:18:10)
    at Class.init (..\node_modules\db-migrate\lib\migration.js:21:24)
    at Class.prototype.(anonymous function) [as init] (..\node_modules\db-migrate\lib\class.js:36:24)
    at new Class (..\node_modules\db-migrate\lib\class.js:49:17)
    at ..\node_modules\db-migrate\api.js:648:21
    at ..\node_modules\db-migrate\api.js:560:7
    at FSReqWrap.oncomplete (fs.js:153:5)

Exception is due to 
41628f758de62d7bc18e3958ddd84ede833f2fbd
Merge pull request #485 from gmanriqueUy/master
fix(create): use same timestamp in every created file

internals.runTimestamp = new Date(); 
is only set when db-migrate is run throu the CLI.

**Comment by gmanriqueUy** [comment]
Ups! I din't notice this. Already working on a PR to fix this. Thanks @TsvetomirGeorgiev for informing on this one.
