### ISSUE TITLE
Unable to run from command line

### ISSUE THREAD

**Issue by ianp** [db-migrate/node-db-migrate#494]
It looks like `0.10.0-beta.23` has changed something related to environment detection. If I try to run the `db-migrate` CLI (with any of `create, `up`, or `down`) args  I get the following error:

```
/Users/ianp/Projects/xxxxxxxx/node_modules/db-migrate/lib/config.js:21
    throw new Error('Environment(s) \'' + env.join(', ') + '\' not found.');
    ^

Error: Environment(s) 'dev, development' not found.
    at Config.exports.setCurrent (/Users/ianp/Projects/xxxxxxxx/node_modules/db-migrate/lib/config.js:21:11)
    at Object.exports.loadObject (/Users/ianp/Projects/xxxxxxxx/node_modules/db-migrate/lib/config.js:202:9)
    at Object.exports.loadFile (/Users/ianp/Projects/xxxxxxxx/node_modules/db-migrate/lib/config.js:99:18)
    at loadConfig (/Users/ianp/Projects/xxxxxxxx/node_modules/db-migrate/api.js:572:18)
    at dbmigrate (/Users/ianp/Projects/xxxxxxxx/node_modules/db-migrate/api.js:127:17)
    at Object.module.exports.getInstance (/Users/ianp/Projects/xxxxxxxx/node_modules/db-migrate/index.js:70:10)
    at /Users/ianp/Projects/xxxxxxxx/node_modules/db-migrate/bin/db-migrate:35:25
    at /Users/ianp/Projects/xxxxxxxx/node_modules/resolve/lib/async.js:45:21
    at ondir (/Users/ianp/Projects/xxxxxxxx/node_modules/resolve/lib/async.js:196:27)
    at onex (/Users/ianp/Projects/xxxxxxxx/node_modules/resolve/lib/async.js:104:32)
```

Reverting to beta 22 (or 21) fixes things again.

**Comment by Skattspa** [comment]
You have to execute every command with 
`--config config/yourjsonName.json -e yourEnvironment`

**Comment by wzrdtales** [comment]
I think this should be solved in the latest version already, feel free to reopen if it shouldn't

**Comment by ulvidamirli** [comment]
I encountered with this issue. Then I solved it by placing `.env` file to `root` instead of `src` folder.
