### ISSUE TITLE
unhandledRejection reason lack of stack

### ISSUE THREAD

**Issue by junchaozhang** [db-migrate/node-db-migrate#495]
when I run the migration, I get `[ERROR] undefined`, and the shell exited,
then I check the code , and found that, in [api.js](https://github.com/db-migrate/node-db-migrate/blob/master/api.js)
```
function registerEvents() {

  process.on('uncaughtException', function(err) {
    log.error(err.stack || err);
    process.exit(1);
  });

  process.on('unhandledRejection', function(reason) {
    log.error(reason.stack);
    process.exit(1);
  });
}
```

then I print the reason, and found that:
```
migratetiger_1  | [ERROR] undefined
migratetiger_1  | { err: null,
migratetiger_1  |   originalErr:
migratetiger_1  |    { Error: ER_BAD_FIELD_ERROR: Unknown column 'run_on' in 'order clause'
migratetiger_1  |        at Query.Sequence._packetToError (/usr/src/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
migratetiger_1  |        at Query.ErrorPacket (/usr/src/app/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
migratetiger_1  |        at Protocol._parsePacket (/usr/src/app/node_modules/mysql/lib/protocol/Protocol.js:279:23)
migratetiger_1  |        at Parser.write (/usr/src/app/node_modules/mysql/lib/protocol/Parser.js:76:12)
migratetiger_1  |        at Protocol.write (/usr/src/app/node_modules/mysql/lib/protocol/Protocol.js:39:16)
migratetiger_1  |        at Socket.<anonymous> (/usr/src/app/node_modules/mysql/lib/Connection.js:103:28)
migratetiger_1  |        at emitOne (events.js:96:13)
migratetiger_1  |        at Socket.emit (events.js:191:7)
migratetiger_1  |        at readableAddChunk (_stream_readable.js:178:18)
migratetiger_1  |        at Socket.Readable.push (_stream_readable.js:136:10)
migratetiger_1  |        at TCP.onread (net.js:559:20)
migratetiger_1  |        --------------------
migratetiger_1  |        at Protocol._enqueue (/usr/src/app/node_modules/mysql/lib/protocol/Protocol.js:145:48)
migratetiger_1  |        at Connection.query (/usr/src/app/node_modules/mysql/lib/Connection.js:208:25)
migratetiger_1  |        at Class.all (/usr/src/app/node_modules/db-migrate-mysql/index.js:391:34)
migratetiger_1  |        at Class.allLoadedMigrations (/usr/src/app/node_modules/db-migrate-base/index.js:540:17)
migratetiger_1  |        at Function.Migration.loadFromDatabase (/usr/src/app/linked_libs/db-migrate/lib/migration.js:359:12)
migratetiger_1  |        at /usr/src/app/linked_libs/db-migrate/lib/migrator.js:156:17
migratetiger_1  |        at /usr/src/app/linked_libs/db-migrate/lib/migration.js:348:5
migratetiger_1  |        at FSReqWrap.oncomplete (fs.js:114:15)
migratetiger_1  |      code: 'ER_BAD_FIELD_ERROR',
migratetiger_1  |      errno: 1054,
migratetiger_1  |      sqlMessage: 'Unknown column \'run_on\' in \'order clause\'',
migratetiger_1  |      sqlState: '42S22',
migratetiger_1  |      index: 0,
migratetiger_1  |      sql: 'SELECT * FROM `migrations` ORDER BY run_on DESC, name DESC' } }
```

so the reason don't have slack, can we log the `reason`?

**Comment by wzrdtales** [comment]
@junchaozhang Edge case yeah, I guess this happened on the unhandledRejection event? Then we probably should the the same as for uncaughtException.

**Comment by junchaozhang** [comment]
GH-11

**Comment by wzrdtales** [comment]
Thanks for putting up the PR :) But you got the wrong reference to the issue, closing manually here.
