### ISSUE TITLE
Cannot run in heroku with SSL on

### ISSUE THREAD

**Issue by apolishch** [db-migrate/node-db-migrate#503]
I am using standard Postgres in Heroku, which has SSL on by default. Whenever I try to run the migrations, I get hit with:

```
[ERROR] error: no pg_hba.conf entry for host "${ip}", user "${user}", database "${database}", SSL off
    at Connection.parseE (/app/node_modules/db-migrate-pg/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/app/node_modules/db-migrate-pg/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/app/node_modules/db-migrate-pg/node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:563:20)
```

My migration command:

```
package.json:

    "migrate": "db-migrate --config migrations-config.js",
    "migrate-up": "npm run migrate up"
```

My migrations-config:
'use strict'

```
import {postgres} from 'config'
import {parse as urlParse} from 'url'

const parsed = urlParse(postgres.connectionUrl)
const auth = parsed.auth.split(':')
const user = auth[0]
const password = auth[1]

export default {
  driver: 'pg',
  user,
  password,
  host: parsed.hostname,
  database: parsed.pathname.substring(1),
  port: parsed.port,
  schema: '${schema}',
  ssl: (process.env.NODE_ENV === 'production')
}

```

and my config.js entry:

```
export const postgres = {
  connectionUrl: process.env.DATABASE_URL
}
```

If I change the ssl to be explicitly true via:
```
ssl: true
``` in the migrations config, the result is the same.

Any suggestions on how to fix this would be amazing!

**Comment by apolishch** [comment]
Eventually I got this to work with:
```
module.exports = {
  dev: {
    driver: 'pg',
    url: postgres.connectionUrl,
    schema: 'flock_auth'
  },
  prod: {
    driver: 'pg',
    schema: 'flock_auth',
    url: postgres.connectionUrl,
    addIfNotExists: {
      sslmode: 'require'
    },
    overwrite: {
      native: true
    }
  }
}

```
and passing the env flag to the command line

**Comment by paulmiller3000** [comment]
@apolishch I know it's been a while, but did you fix this in a public repo? I ran into a similar problem today, though it looks like our setups differ. Would love to see the full repo.

**Comment by shto** [comment]
For others coming here at a later time, this is what helped me.

I am using a `database.json` file as the default configuration. Turns out Heroku already offers a default JSON config for the database, so in the particular environment you are running the app in, all you need to add is this:

```
    "staging": {
      "overwrite": {
        "driver": "pg",
        "ssl": {
          "rejectUnauthorized": false
        }
      }
    }
```

`rejectUnauthorized` is the key element here.

**Comment by Alenius** [comment]
Thanks @shto, you solved my problem!

Just to be overly clear for people who are bad at reading the docs (as myself). You have to pass in the explicit env you defined in your `database.json` when running the migration, e.g.:

```
"postinstall": "yarn db:migrate:up --env staging"
```

**Comment by desmondmc** [comment]
@shto @Alenius thanks for the help! You saved my life.
