### ISSUE TITLE
Cannot find module './connect'

### ISSUE THREAD

**Issue by pc-jedi** [db-migrate/node-db-migrate#520]
With version 0.10.0 I got an error if I execute the following line.

```
./node_modules/.bin/db-migrate db:create test -e dev
```

Bellow you can see the stacktrace. For me it looks like you want to require the `connect.js` file in the root folder of db-migrate, right?
```
Unhandled rejection Error: Cannot find module './connect'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at executeDB (/home/me/test/node_modules/db-migrate/lib/commands/db.js:7:15)
    at run (/home/me/test/node_modules/db-migrate/lib/commands/run.js:76:19)
    at dbmigrate.run (/home/me/test/node_modules/db-migrate/api.js:439:16)
    at /home/me/test/node_modules/db-migrate/bin/db-migrate:36:19
    at tryCatcher (/home/me/test/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/me/test/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/me/test/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/me/test/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/me/test/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/me/test/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/me/test/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/me/test/node_modules/bluebird/js/release/async.js:17:14)

```

**Comment by wzrdtales** [comment]
Thank you for reporting this bug!

Was fixed and published under 

+ db-migrate@0.10.1
