### ISSUE TITLE
what's this?!

### ISSUE THREAD

**Issue by mengjiaqi** [db-migrate/node-db-migrate#521]
when i try to run

```
db-migrate up
```

it shows me like this..

```
Unhandled rejection Error: [object Object]
    at Object.exports.connect (/Users/jackie/Workspace/bitniex/exchange/node_modules/db-migrate/lib/driver/index.js:77:11)
    at Object.exports.connect (/Users/jackie/Workspace/bitniex/exchange/node_modules/db-migrate/connect.js:15:10)
    at /Users/jackie/Workspace/bitniex/exchange/node_modules/db-migrate/lib/commands/up.js:15:13
    at tryCatcher (/Users/jackie/Workspace/bitniex/exchange/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/jackie/Workspace/bitniex/exchange/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/Users/jackie/Workspace/bitniex/exchange/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromiseCtx (/Users/jackie/Workspace/bitniex/exchange/node_modules/bluebird/js/release/promise.js:596:10)
    at Async._drainQueue (/Users/jackie/Workspace/bitniex/exchange/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/Users/jackie/Workspace/bitniex/exchange/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/Users/jackie/Workspace/bitniex/exchange/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
```

**Comment by mengjiaqi** [comment]
here is my migration file
```javascript
'use strict';

exports.up = function(db) {
  return db.createTable('currency', {
    id: { type: 'string', primaryKey: true },
    name: 'string',
    symbol: 'string'
  });
};

exports.down = function(db) {
  return null;
};

```

**Comment by wzrdtales** [comment]
Hey @mengjiaqi ,

unfortunately we can't help you if you don't provide us all informations necessary to reproduce your case.

This means, **always** post:
- used node version
- used npm version
- used db-migrate version
- used driver and its version
- used plugins
- full output of the verbose run
- in complex cases a full gist, as an executable proof
- if necessary used migrations and configuration details (**replace sensible informations before posting configs!**)
- if necessary code samples

As soon as you provide us all information needed, we have an easy way to reproduce your problem and provide you with the help or bugfix you need.

Thank you.

**Comment by wzrdtales** [comment]
To note your migration you posted is also wrong, the way you noted `name` and `symbol´ are illegal.

**Comment by gregorypease280** [comment]
@mengjiaqi  @wzrdtales 
    at Object.exports.connect (/Users/jackie/Workspace/bitniex/exchange/node_modules/db-migrate/lib/driver/index.js:77:11)
 is failing to print the correct error.
```
'No such driver found, please try to install it via ' +
              'npm install db-migrate-' +
              config.driver +
```...
@mengjiaqi for my case I ran 'npm install db-migrate-mysql' which fixed the problem

**Comment by Pinqvin** [comment]
I recently upgraded from 0.9.x to 0.10.1 and my migrations are failing with this error. Investigating further, it looks like the driver loading fails (at least when using only DATABASE_URL based configuration). The driver loading tries to require `db-migrate-pg` twice, then `../../../db-migrate-pg` and `./pg` as a last resort.

None of these are found after my 0.9 -> 0.10 upgrade, since the local pg file doesn't exist anymore and I don't have `db-migrate-pg` installed. Should I? If I should, this is probably something that should be documented better in breaking changes or in the documentation (quickly glancing through, I couldn't see any mentions of db-migrate specific drivers anywhere).

Anyway, I continued by installing `db-migrate-pg@0.2.5`. And this time connecting works! But I noticed another issue: if the migration fails for some reason, the API error is again `Error: [object Object]`, and it happens at db-migrate/lib/commands/on-complete.js:13:9. I'll try and produce a minimal sample of this issue later, but basically the error logging seems to be really problematic right now

**Comment by wzrdtales** [comment]
@Pinqvin This is wanted, expected and noted in the breaking changes. Simply: drivers have been removed from the core, so yes, install the driver you want to use.

**Comment by wzrdtales** [comment]
About the error. this are two erros in one, due to the way db-migrate reaches this point in the application. Needs a revisit though.

**Comment by wzrdtales** [comment]
related and duplicated with #524
