### ISSUE TITLE
db-migrate fails to show version if database.json missing

### ISSUE THREAD

**Issue by vladimirtiukhtin** [db-migrate/node-db-migrate#568]
## I'm submitting a...
 - [ ] Bug report

## Current behavior
```
db-migrate version
[ERROR] Error: Could not find database config file '//database.json'
    at Object.exports.loadFile (/usr/lib/node_modules/db-migrate/lib/config.js:48:13)
    at loadConfig (/usr/lib/node_modules/db-migrate/lib/commands/helper/load-config.js:12:18)
    at new dbmigrate (/usr/lib/node_modules/db-migrate/api.js:68:43)
    at Object.module.exports.getInstance (/usr/lib/node_modules/db-migrate/index.js:62:10)
    at /usr/lib/node_modules/db-migrate/bin/db-migrate:32:25
    at /usr/lib/node_modules/db-migrate/node_modules/resolve/lib/async.js:52:13
    at processDirs (/usr/lib/node_modules/db-migrate/node_modules/resolve/lib/async.js:184:39)
    at ondir (/usr/lib/node_modules/db-migrate/node_modules/resolve/lib/async.js:199:13)
    at load (/usr/lib/node_modules/db-migrate/node_modules/resolve/lib/async.js:82:43)
    at onex (/usr/lib/node_modules/db-migrate/node_modules/resolve/lib/async.js:107:17)
```
## Expected behavior
Current version in command output

**Comment by Surendra99** [comment]
I think this issue has been fixed.

**Comment by wzrdtales** [comment]
not a command, it is 

```
db-migrate --version
```
