### ISSUE TITLE
Not using ssl and sslmode parameters with Heroku

### ISSUE THREAD

**Issue by paulmiller3000** [db-migrate/node-db-migrate#676]
## I'm submitting a...
 - [x ] Bug report  
 - [ ] Feature request
 - [ ] Question

## Current behavior
When deploying to Heroku, I receive the following error:

```
[ERROR] AssertionError [ERR_ASSERTION]: ifError got unwanted exception: no pg_hba.conf entry for host "{redacted}", user "{redacted}", database "{redacted}", SSL off
    at module.exports (/app/node_modules/db-migrate/lib/commands/helper/assert.js:9:14)
```

Below is my database.json file. The environment in question is "production."

```
{
  "development": {
    "driver": "pg",
    "user": {"ENV": "DATABASE_USER"},
    "password": {"ENV": "DATABASE_PASSWORD"},
    "host": {"ENV": "DATABASE_HOST"},
    "database": {"ENV": "DATABASE_NAME"},
    "schema": {"ENV": "DATABASE_SCHEMA"}
  },

  "staging": {
    "driver": "pg",
    "user": {"ENV": "DATABASE_USER"},
    "password": {"ENV": "DATABASE_PASSWORD"},
    "host": {"ENV": "DATABASE_HOST"},
    "database": {"ENV": "DATABASE_NAME"},
    "schema": {"ENV": "DATABASE_SCHEMA"}
  },

  "production": {
    "driver": "pg",
    "url": {"ENV": "DATABASE_URL"},
    "ssl": true,
    "sslmode": "require"
  }
}
```

I hard-coded the ssl and sslmode values after first trying them as environment variables.

I checked and the proper database name and user are being read from the URL.

## Expected behavior
db-migrate attempts to connect using ssl.

## Environment

<pre><code>
db-migrate version: 0.11.6
db-migrate driver with versions: db-migrate-pg 1.0.0

Additional information:
- Node version: 12.3.1
- Platform:  Windows 10

</code></pre>

**Comment by paulmiller3000** [comment]
Update: I edited my Procfile as follows:

```
release: db-migrate up -v -e $ENVIRONMENT
web: node server.js
```
Here's the verbose output:

> [INFO] Detected and using the projects local version of db-migrate. '/app/node_modules/db-migrate/index.js'
> [INFO] Using development settings: {
>   driver: 'pg',
>   user: '{redacted}',
>   password: '******',
>   host: '{redacted}',
>   database: '{redacted}',
>   schema: 'public'
> }
> [INFO] require: db-migrate-pg
> [INFO] connecting
> [ERROR] AssertionError [ERR_ASSERTION]: ifError got unwanted exception: no pg_hba.conf entry for host "{redacted}", user "{redacted}", database "{redacted}", SSL off
>     at module.exports (/app/node_modules/db-migrate/lib/commands/helper/assert.js:9:14)
>     at /app/node_modules/db-migrate/lib/commands/up.js:19:14
>     at /app/node_modules/db-migrate/connect.js:17:7
>     at /app/node_modules/db-migrate/lib/driver/index.js:95:9
>     at /app/node_modules/db-migrate-pg/index.js:672:7
>     at Connection.connectingErrorHandler (/app/node_modules/pg/lib/client.js:194:14)
>     at Connection.emit (events.js:311:20)
>     at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:134:12)
>     at Connection.parseE (/app/node_modules/pg/lib/connection.js:614:13)
>     at Connection.parseMessage (/app/node_modules/pg/lib/connection.js:413:19)
>     at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:129:22)
>     at Socket.emit (events.js:311:20)
>     at addChunk (_stream_readable.js:294:12)
>     at readableAddChunk (_stream_readable.js:275:11)
>     at Socket.Readable.push (_stream_readable.js:209:10)
>     at TCP.onStreamRead (internal/stream_base_commons.js:186:23)

**Comment by paulmiller3000** [comment]
SUCCESS! This last issue was my fault: I'd added a file named `migrations-config.js` to the `migrations` folder as a troubleshooting step I'd found somewhere along the way. That's a BIG no-no: ONLY migrations should go in the migrations folder (obviously).

Hopefully this helps someone else along the way.

**Comment by desmondmc** [comment]
@paulmiller3000 you just saved my life. I was so stuck on this, I don't even want to imagine how much time i would have wasted if I hadn't have found this issue. 

Thanks so much! 🤗

**Comment by paulmiller3000** [comment]
@desmondmc Glad I could help!

**Comment by desmondmc** [comment]
I'll add my issues, just in case it's helpful to future readers.

- The problem started happening to me after updating from a hobby heroku postgres db to standard.
- It seems that i was never actually connecting with ssl and it was just working before because the heroku hobby postgres allows that.
- As @paulmiller3000 pointed out db-migrate kept using my `dev` config for some reason, even though i was passing `-e prod` to the db-migrate command (`heroku run db-migrate up --config database.json -e prod --app my-app`). It kept saying something about "prod not valid avoid using ';'"
- Nothing i could do would force db-migrate to use my production config. In the end the only thing that worked was changing my config file to use `NODE_ENV` to choose the environment:

```
{
  "defaultEnv": {"ENV": "NODE_ENV"},
  "dev": {
    "driver": "pg",
    "host": "localhost",
    "database": "hevy"
  },
  "production": {
    "driver": "pg",
    "url": { "ENV": "HEROKU_POSTGRESQL_SILVER_URL" },
    "addIfNotExists": {
      "sslmode": "require"
    },
    "overwrite": {
      "native": true
    }
  }
}
```
