### ISSUE TITLE
db-migrate up  [ERROR] AssertionError [ERR_ASSERTION]: ifError got unwanted exception: password authentication failed for user "hassan"

### ISSUE THREAD

**Issue by HassanElwany** [db-migrate/node-db-migrate#783]
at module.exports (/home/hassan/Desktop/GitHup Work/StoreProjectUdacity/node_modules/db-migrate/lib/commands/helper/assert.js:9:14)
    at /home/hassan/Desktop/GitHup Work/StoreProjectUdacity/node_modules/db-migrate/lib/commands/up.js:19:14
    at /home/hassan/Desktop/GitHup Work/StoreProjectUdacity/node_modules/db-migrate/connect.js:17:7
    at /home/hassan/Desktop/GitHup Work/StoreProjectUdacity/node_modules/db-migrate/lib/driver/index.js:95:9
    at Client._connectionCallback (/home/hassan/Desktop/GitHup Work/StoreProjectUdacity/node_modules/db-migrate-pg/index.js:710:7)
    at Client._handleErrorWhileConnecting (/home/hassan/Desktop/GitHup Work/StoreProjectUdacity/node_modules/pg/lib/client.js:305:19)
    at Client._handleErrorMessage (/home/hassan/Desktop/GitHup Work/StoreProjectUdacity/node_modules/pg/lib/client.js:325:19)
    at Connection.emit (node:events:527:28)
    at /home/hassan/Desktop/GitHup Work/StoreProjectUdacity/node_modules/pg/lib/connection.js:114:12
    at Parser.parse (/home/hassan/Desktop/GitHup Work/StoreProjectUdacity/node_modules/pg-protocol/dist/parser.js:40:17)
    at Parser.parseErrorMessage (/home/hassan/Desktop/GitHup Work/StoreProjectUdacity/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/hassan/Desktop/GitHup Work/StoreProjectUdacity/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/hassan/Desktop/GitHup Work/StoreProjectUdacity/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/hassan/Desktop/GitHup Work/StoreProjectUdacity/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)

**Comment by wzrdtales** [comment]
not a ticket, spam
